In [1]:
import numpy as np

print("=" * 60)
print("UNDERSTANDING SCALARS, VECTORS, MATRICES, AND TENSORS")
print("=" * 60)

# --------------------------------------------------
# VECTOR (1D Tensor)
# A simple list of numbers
# Shape: (4,)
# --------------------------------------------------
vector = np.array([3.9, 5.6, 6.7, 8.9])

print("\n1. VECTOR")
print("A vector is a collection of numbers arranged in a single dimension.")
print(f"Vector = {vector}")
print(f"Shape  = {vector.shape}")

# --------------------------------------------------
# MATRIX (2D Tensor)
# Rows × Columns
# Shape: (3, 4)
# --------------------------------------------------
matrix = np.array([
    [3.9, 5.6, 6.7, 8.9],
    [5.1, 4.5, 7.0, 8.0],
    [6.7, 8.0, 9.0, 0.1]
])

print("\n2. MATRIX")
print("A matrix is a collection of vectors stacked together.")
print(f"Matrix:\n{matrix}")
print(f"Shape = {matrix.shape}")

# --------------------------------------------------
# TENSOR (3D Tensor)
# Multiple matrices stacked together
#
# Shape: (1, 3, 4)
#
# Think of this as:
# Number of Matrices × Rows × Columns
# --------------------------------------------------
tensor = np.array([
    [
        [3.9, 5.6, 6.7, 8.9],
        [5.1, 4.5, 7.0, 8.0],
        [6.7, 8.0, 9.0, 0.1]
    ]
])

print("\n3. TENSOR")
print("A tensor is a higher-dimensional generalization of matrices.")
print(f"Tensor:\n{tensor}")
print(f"Shape = {tensor.shape}")

# --------------------------------------------------
# Parameters of a simple linear model
#
# y = mx + c
#
# m -> Weight (slope)
# c -> Bias (intercept)
#
# In Deep Learning:
# m represents learnable weights
# c represents learnable biases
# --------------------------------------------------
m = 0.1
c = 0.4

print("\n4. MODEL PARAMETERS")
print(f"Weight (m) = {m}")
print(f"Bias   (c) = {c}")

# --------------------------------------------------
# Applying the linear equation:
#
# y = mx + c
#
# NumPy automatically performs this operation
# on every element of the tensor.
#
# This is called Vectorized Computation.
# --------------------------------------------------
print("\nApplying the equation:")
print("y = m * x + c")

y = m * tensor + c

print("\nOutput Tensor:")
print(y)

print(f"\nOutput Shape = {y.shape}")

# --------------------------------------------------
# Key Observation
# --------------------------------------------------
print("\n" + "=" * 60)
print("IMPORTANT OBSERVATION")
print("=" * 60)

print("""
Previously we used:

    y = mx + c

with scalar values.

Now x is a Tensor.

NumPy automatically applies the same equation
to every element inside the tensor.

This is exactly how modern Deep Learning frameworks
such as PyTorch and TensorFlow operate.

Instead of learning from a single number,
the model learns from thousands or millions of values
simultaneously.

This gives neural networks much greater
representation power.
""")

UNDERSTANDING SCALARS, VECTORS, MATRICES, AND TENSORS

1. VECTOR
A vector is a collection of numbers arranged in a single dimension.
Vector = [3.9 5.6 6.7 8.9]
Shape  = (4,)

2. MATRIX
A matrix is a collection of vectors stacked together.
Matrix:
[[3.9 5.6 6.7 8.9]
 [5.1 4.5 7.  8. ]
 [6.7 8.  9.  0.1]]
Shape = (3, 4)

3. TENSOR
A tensor is a higher-dimensional generalization of matrices.
Tensor:
[[[3.9 5.6 6.7 8.9]
  [5.1 4.5 7.  8. ]
  [6.7 8.  9.  0.1]]]
Shape = (1, 3, 4)

4. MODEL PARAMETERS
Weight (m) = 0.1
Bias   (c) = 0.4

Applying the equation:
y = m * x + c

Output Tensor:
[[[0.79 0.96 1.07 1.29]
  [0.91 0.85 1.1  1.2 ]
  [1.07 1.2  1.3  0.41]]]

Output Shape = (1, 3, 4)

IMPORTANT OBSERVATION

Previously we used:

    y = mx + c

with scalar values.

Now x is a Tensor.

NumPy automatically applies the same equation
to every element inside the tensor.

This is exactly how modern Deep Learning frameworks
such as PyTorch and TensorFlow operate.

Instead of learning from a single

---

### Matrix Multiplication: From Scalars to Learnable Feature Combinations

Until now, we used:

$$
y = mx + c
$$

where `m` and `x` were multiplied element-wise.

In Deep Learning, we rarely use simple scalar multiplication. Instead, we use **matrix multiplication**, because it allows the network to learn relationships between multiple features simultaneously.

---

### Code

```python
import numpy as np

# Weight Matrix
m = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Input Vector
x = np.array([4, -1, 3])

# Matrix Multiplication
g = m @ x

print(f"m.shape = {m.shape}")
print(f"x.shape = {x.shape}")
print(f"g.shape = {g.shape}")

print(f"\nOutput = {g}")
```

---

### What is Happening?

The shape of the operands:

```text
m.shape = (3, 3)
x.shape = (3,)
```

Matrix multiplication performs:

$$
(3 \times 3)
\times
(3 \times 1)
============

(3 \times 1)
$$

Result:

$$
g =
\begin{bmatrix}
1 & 2 & 3\
4 & 5 & 6\
7 & 8 & 9
\end{bmatrix}
\begin{bmatrix}
4\
-1\
3
\end{bmatrix}
$$

---

### Row-by-Row Computation

First row:

$$
(1)(4)+(2)(-1)+(3)(3) = 

11
$$

Second row:

$$
(4)(4)+(5)(-1)+(6)(3) = 

29
$$

Third row:

$$
(7)(4)+(8)(-1)+(9)(3) = 

47
$$

Final output:

$$
g=
\begin{bmatrix}
11\,
29\,
47
\end{bmatrix}
$$

---

### Why Is This Better Than Scalar Multiplication?

With scalar multiplication:

$$
y = wx
$$

one weight learns one relationship.

Example:

```text
Height → Weight
```

Only a single relationship is captured.

---

With matrix multiplication:

$$
g = Wx
$$

each output neuron learns from **all input features simultaneously**.

```text
Input Features
↓
[ Height ]
[ Weight ]
[ Age    ]
```

Every output combines information from every input.

```text
Output 1 ← Height + Weight + Age
Output 2 ← Height + Weight + Age
Output 3 ← Height + Weight + Age
```

This gives the network much greater expressive power.

---

### Deep Learning Interpretation

Think of:

$$
x
$$

as features extracted from an image.

Example:

```text
x =
[
 edge_strength,
 texture_score,
 color_intensity
]
```

The weight matrix:

$$
W
$$

learns how important each feature is.

After multiplication:

$$
g = Wx
$$

the network creates a new representation of the image.

This process is repeated hundreds of times across many layers.

---

### Why We Need Matrix Multiplication

1. **Combines multiple features together**
2. **Learns complex relationships**
3. **Creates richer representations**
4. **Runs efficiently on GPUs**
5. **Forms the foundation of neural networks**

---

### Key Takeaway

Element-wise multiplication:

$$
y = mx
$$

learns from individual values.

Matrix multiplication:

$$
g = Wx
$$

learns interactions between multiple features at once.

> Modern AI models are essentially a massive sequence of matrix multiplications followed by non-linear activation functions. This is how neural networks transform raw data into meaningful representations.


---

## Tensor Shape understanding

In [2]:
import numpy as np

print("=" * 60)
print("UNDERSTANDING TENSOR SHAPES")
print("=" * 60)

# --------------------------------------------------
# Create 75 numbers
# --------------------------------------------------
data = np.arange(75)

print(f"Original Shape = {data.shape}")
print(f"Total Elements = {data.size}")

# --------------------------------------------------
# Reshape into a tensor of shape (3, 5, 5)
# --------------------------------------------------
tensor = data.reshape(3, 5, 5)

print("\nAfter Reshaping:")
print(f"Tensor Shape = {tensor.shape}")

print("\nTensor Contents:")
print(tensor)

# --------------------------------------------------
# Understanding dimensions
# --------------------------------------------------
print("\nDimension Breakdown:")
print(f"Dimension 0 = {tensor.shape[0]}")
print(f"Dimension 1 = {tensor.shape[1]}")
print(f"Dimension 2 = {tensor.shape[2]}")

print("\nInterpretation:")
print("We have 3 matrices")
print("Each matrix has 5 rows")
print("Each row has 5 columns")

UNDERSTANDING TENSOR SHAPES
Original Shape = (75,)
Total Elements = 75

After Reshaping:
Tensor Shape = (3, 5, 5)

Tensor Contents:
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]

 [[50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]]]

Dimension Breakdown:
Dimension 0 = 3
Dimension 1 = 5
Dimension 2 = 5

Interpretation:
We have 3 matrices
Each matrix has 5 rows
Each row has 5 columns


##### Tensor re-shaping

In [3]:
import numpy as np

print("=" * 60)
print("UNDERSTANDING SHAPES, NDIM AND RESHAPE")
print("=" * 60)

# --------------------------------------------------
# Create a small RGB image
#
# Shape = (3, 2, 2)
#
# Interpretation:
# 3 Channels
# 2 Height
# 2 Width
#
# In real images:
# Channel 0 -> Red
# Channel 1 -> Green
# Channel 2 -> Blue
# --------------------------------------------------
img = np.random.randint(0, 10, (3, 2, 2))

print("\nImage Tensor:")
print(img)

print(f"\nShape = {img.shape}")
print(f"Number of Dimensions = {img.ndim}")

print("\nHow to read (3, 2, 2)?")
print("3 Channels")
print("2 Rows (Height)")
print("2 Columns (Width)")

# --------------------------------------------------
# Another tensor
# --------------------------------------------------
e = np.random.randint(0, 10, (2, 2, 2))

print("\n" + "-" * 60)
print("Original Tensor e")
print("-" * 60)

print(e)
print(f"Shape = {e.shape}")

# --------------------------------------------------
# Reshape does NOT change data
# It only changes how we view it
#
# (2, 2, 2)
# Total Elements = 8
#
# (1, 4, 2)
# Total Elements = 8
# --------------------------------------------------
e_reshaped = e.reshape(1, 4, 2)

print("\nAfter Reshape:")
print(e_reshaped)

print(f"New Shape = {e_reshaped.shape}")

print("\nNotice:")
print("The numbers are identical.")
print("Only the organization changed.")

# --------------------------------------------------
# Create another image
# --------------------------------------------------
img = np.random.randint(0, 10, (2, 3, 3))

print("\n" + "-" * 60)
print("NEW IMAGE")
print("-" * 60)

print(img)

print(f"\nShape = {img.shape}")

print("\nHow to read (2, 3, 3)?")
print("2 Channels")
print("3 Height")
print("3 Width")

# --------------------------------------------------
# Flattening an image
#
# Original Shape:
# (2, 3, 3)
#
# Total Elements:
# 2 × 3 × 3 = 18
# --------------------------------------------------
print("\nFlattening the image...")

flat_img = img.reshape(1, 2 * 3 * 3)

print(f"New Shape = {flat_img.shape}")

print("\nFlattened Image:")
print(flat_img)

print("\nExplanation:")
print("reshape(1, 18) means:")
print("1 Row")
print("18 Columns")

# --------------------------------------------------
# NumPy can automatically calculate dimensions
# using -1
# --------------------------------------------------
auto_flat = img.reshape(1, -1)

print("\nUsing reshape(1, -1)")
print(f"Shape = {auto_flat.shape}")

print("\n'-1' tells NumPy:")
print("'You figure out this dimension for me automatically.'")

print("\nKey Lesson:")
print("reshape never changes the data.")
print("It only changes how we interpret the same data.")

UNDERSTANDING SHAPES, NDIM AND RESHAPE

Image Tensor:
[[[5 8]
  [6 5]]

 [[7 8]
  [8 4]]

 [[9 8]
  [9 2]]]

Shape = (3, 2, 2)
Number of Dimensions = 3

How to read (3, 2, 2)?
3 Channels
2 Rows (Height)
2 Columns (Width)

------------------------------------------------------------
Original Tensor e
------------------------------------------------------------
[[[1 4]
  [3 3]]

 [[9 2]
  [9 8]]]
Shape = (2, 2, 2)

After Reshape:
[[[1 4]
  [3 3]
  [9 2]
  [9 8]]]
New Shape = (1, 4, 2)

Notice:
The numbers are identical.
Only the organization changed.

------------------------------------------------------------
NEW IMAGE
------------------------------------------------------------
[[[2 1 9]
  [8 1 6]
  [0 9 3]]

 [[1 0 1]
  [2 5 6]
  [1 9 0]]]

Shape = (2, 3, 3)

How to read (2, 3, 3)?
2 Channels
3 Height
3 Width

Flattening the image...
New Shape = (1, 18)

Flattened Image:
[[2 1 9 8 1 6 0 9 3 1 0 1 2 5 6 1 9 0]]

Explanation:
reshape(1, 18) means:
1 Row
18 Columns

Using reshape(1, -1)